import { ToolCategory, ToolDefinition } from "@/types";
export type { ToolCategory, ToolDefinition };

export const CATEGORIES_CONFIG: Array<{
  id: ToolCategory;
  name: string;
  description: string;
  icon: string;
  badge?: string;
}> = [
  {
    id: "convert-to-pdf",
    name: "Convert to PDF",
    description: "Transform Office docs, images, markup, and raw text into pristine standard PDF files.",
    icon: "FileUp",
  },
  {
    id: "convert-from-pdf",
    name: "Convert from PDF",
    description: "Extract and export PDFs into editable Word, spreadsheets, presentations, and image files.",
    icon: "FileDown",
  },
  {
    id: "organize",
    name: "Organize PDF",
    description: "Merge, split, extract, rotate, reorder, and structure pages with visual precision.",
    icon: "Layers",
  },
  {
    id: "compress",
    name: "Compress & Optimize",
    description: "Reduce file sizes while preserving crisp text, vectors, and image clarity.",
    icon: "Minimize2",
    badge: "Fast",
  },
  {
    id: "edit",
    name: "Edit PDF",
    description: "Add annotations, shapes, text callouts, stamps, signatures, and page numbering.",
    icon: "PenTool",
  },
  {
    id: "security",
    name: "PDF Security",
    description: "Protect with enterprise encryption, unlock passwords, apply watermarks, and redact data.",
    icon: "ShieldCheck",
  },
  {
    id: "ocr",
    name: "OCR & Text",
    description: "Convert scanned documents and images into searchable, selectable text & tables.",
    icon: "ScanText",
    badge: "AI Powered",
  },
  {
    id: "ai",
    name: "AI Document Suite",
    description: "Chat with PDFs, summarize executive reports, compare versions, and extract structured data.",
    icon: "Sparkles",
    badge: "Smart",
  },
];

export const TOOLS_REGISTRY: ToolDefinition[] = [
  // ================= CONVERT TO PDF =================
  {
    id: "word-to-pdf",
    slug: "word-to-pdf",
    name: "Word to PDF",
    description: "Convert DOC and DOCX documents into high-quality PDF files with exact formatting.",
    longDescription:
      "Transform Microsoft Word (.docx, .doc) files into universally compatible, standard PDF documents preserving fonts, layout, headings, and images.",
    category: "convert-to-pdf",
    categoryLabel: "Convert to PDF",
    iconName: "FileText",
    badge: "Popular",
    acceptedFormats: [".docx", ".doc", ".dotx"],
    outputFormat: "pdf",
    maxFiles: 10,
    maxSizeMb: 50,
    features: [
      "Preserves original typography, headers, footers & tables",
      "Converts embedded charts and raster images cleanly",
      "Generates search-indexed PDF bookmarks from Word headings",
      "Instant client & server fallback conversion pipeline",
    ],
    faqs: [
      {
        question: "Will my Word formatting change after conversion?",
        answer: "No, DocuForge parses style definitions, margins, tables, and embedded graphics to render exact 1:1 PDF reproductions.",
      },
      {
        question: "Are DOC and DOCX both supported?",
        answer: "Yes, both legacy Word 97-2003 (.doc) and modern Office Open XML (.docx) formats are supported.",
      },
    ],
    isImplemented: true,
  },
  {
    id: "jpg-to-pdf",
    slug: "jpg-to-pdf",
    name: "JPG to PDF",
    description: "Transform JPG images into a single multi-page PDF or individual documents.",
    longDescription:
      "Combine individual photos or image batches into crisp, multi-page PDF documents. Configure page orientation, margins, and canvas fitting.",
    category: "convert-to-pdf",
    categoryLabel: "Convert to PDF",
    iconName: "Image",
    badge: "Popular",
    acceptedFormats: [".jpg", ".jpeg"],
    outputFormat: "pdf",
    maxFiles: 50,
    maxSizeMb: 50,
    features: [
      "Custom page sizing (A4, Letter, Auto-fit)",
      "Orientation selection (Portrait, Landscape, Auto)",
      "Configurable margins (None, Small, Large)",
      "Drag-and-drop image reordering before export",
    ],
    faqs: [
      {
        question: "Can I combine multiple JPGs into one PDF file?",
        answer: "Yes! You can upload as many JPGs as you want, reorder them visually, and generate a unified multi-page PDF.",
      },
    ],
    isImplemented: true,
  },
  {
    id: "png-to-pdf",
    slug: "png-to-pdf",
    name: "PNG to PDF",
    description: "Convert PNG graphics with transparency preservation into crisp PDF pages.",
    longDescription:
      "Turn PNG screenshots, mockups, and artwork into high-resolution PDF pages with optional background color selection.",
    category: "convert-to-pdf",
    categoryLabel: "Convert to PDF",
    iconName: "FileImage",
    acceptedFormats: [".png"],
    outputFormat: "pdf",
    maxFiles: 50,
    maxSizeMb: 50,
    features: ["Alpha transparency handling", "Lossless conversion", "Multi-image bundling", "Page layout customization"],
    isImplemented: true,
  },
  {
    id: "excel-to-pdf",
    slug: "excel-to-pdf",
    name: "Excel to PDF",
    description: "Convert XLS and XLSX spreadsheets into readable, page-fitted PDF reports.",
    longDescription: "Turn tabular spreadsheet workbooks into neatly paginated, executive-ready PDF tables.",
    category: "convert-to-pdf",
    categoryLabel: "Convert to PDF",
    iconName: "Table",
    acceptedFormats: [".xlsx", ".xls", ".csv"],
    outputFormat: "pdf",
    maxFiles: 5,
    maxSizeMb: 30,
    features: ["Auto sheet fitting", "Gridlines preservation", "Print area recognition", "Multiple worksheet support"],
    isImplemented: true,
  },
  {
    id: "powerpoint-to-pdf",
    slug: "powerpoint-to-pdf",
    name: "PowerPoint to PDF",
    description: "Convert PPT and PPTX slide decks into presentation-grade PDF files.",
    longDescription: "Export presentation slides into clean PDF handouts, retaining aspect ratios, vectors, and speaker notes.",
    category: "convert-to-pdf",
    categoryLabel: "Convert to PDF",
    iconName: "Presentation",
    acceptedFormats: [".pptx", ".ppt"],
    outputFormat: "pdf",
    maxFiles: 5,
    maxSizeMb: 50,
    features: ["Slide aspect ratio preservation", "Vector shape fidelity", "Slide notes support"],
    isImplemented: true,
  },
  {
    id: "html-to-pdf",
    slug: "html-to-pdf",
    name: "HTML to PDF",
    description: "Render web pages, HTML snippets, and styled documents to PDF.",
    longDescription: "Render modern HTML5 and CSS stylesheets into standard PDF documents with custom print media queries.",
    category: "convert-to-pdf",
    categoryLabel: "Convert to PDF",
    iconName: "Code",
    acceptedFormats: [".html", ".htm"],
    outputFormat: "pdf",
    maxFiles: 5,
    maxSizeMb: 20,
    features: ["CSS3 styling support", "Print emulation", "Embedded asset bundling"],
    isImplemented: true,
  },
  {
    id: "txt-to-pdf",
    slug: "txt-to-pdf",
    name: "TXT to PDF",
    description: "Convert plain text files into neatly formatted, paginated PDF documents.",
    longDescription: "Convert ASCII and UTF-8 plain text documents into clean PDF pages with custom typography and line-heights.",
    category: "convert-to-pdf",
    categoryLabel: "Convert to PDF",
    iconName: "FileCode",
    acceptedFormats: [".txt"],
    outputFormat: "pdf",
    maxFiles: 10,
    maxSizeMb: 10,
    features: ["UTF-8 encoding", "Monospace & Serif options", "Automated page breaks"],
    isImplemented: true,
  },
  {
    id: "markdown-to-pdf",
    slug: "markdown-to-pdf",
    name: "Markdown to PDF",
    description: "Transform Markdown (.md) documents with code highlighting into formatted PDF articles.",
    longDescription: "Compile GitHub-flavored markdown with syntax highlighting, tables, callouts, and math into PDF reports.",
    category: "convert-to-pdf",
    categoryLabel: "Convert to PDF",
    iconName: "BookOpen",
    acceptedFormats: [".md", ".markdown"],
    outputFormat: "pdf",
    maxFiles: 10,
    maxSizeMb: 10,
    features: ["GitHub Flavored Markdown", "Syntax code blocks", "Table rendering"],
    isImplemented: true,
  },

  // ================= CONVERT FROM PDF =================
  {
    id: "pdf-to-word",
    slug: "pdf-to-word",
    name: "PDF to Word",
    description: "Convert PDF documents into editable Microsoft Word (.docx) documents.",
    longDescription:
      "Extract text, paragraphs, headings, and formatting from PDF files into editable DOCX files ready for Microsoft Word, Google Docs, or LibreOffice.",
    category: "convert-from-pdf",
    categoryLabel: "Convert from PDF",
    iconName: "FileSpreadsheet",
    badge: "Popular",
    acceptedFormats: [".pdf"],
    outputFormat: "docx",
    maxFiles: 5,
    maxSizeMb: 50,
    features: [
      "Paragraph flow and text reconstruction",
      "Font size & styling mapping",
      "Table extraction & row-column formatting",
      "Scanned OCR fallback pipeline for scanned files",
    ],
    faqs: [
      {
        question: "Can I edit the generated Word file?",
        answer: "Yes, the converted .docx file is completely editable in Microsoft Word, LibreOffice, Apple Pages, and Google Docs.",
      },
    ],
    isImplemented: true,
  },
  {
    id: "pdf-to-jpg",
    slug: "pdf-to-jpg",
    name: "PDF to JPG",
    description: "Extract every PDF page into high-resolution JPG images or download as a ZIP archive.",
    longDescription:
      "Render individual PDF pages into crisp, vibrant JPG image files at customizable DPI resolutions (150, 300 DPI).",
    category: "convert-from-pdf",
    categoryLabel: "Convert from PDF",
    iconName: "FileImage",
    badge: "Popular",
    acceptedFormats: [".pdf"],
    outputFormat: "zip",
    maxFiles: 5,
    maxSizeMb: 50,
    features: [
      "High DPI rendering (150 DPI standard, 300 DPI ultra)",
      "Individual page download or one-click ZIP archive",
      "Custom page range selection",
      "Client-side canvas hardware acceleration",
    ],
    isImplemented: true,
  },
  {
    id: "pdf-to-png",
    slug: "pdf-to-png",
    name: "PDF to PNG",
    description: "Render PDF pages into lossless PNG graphics with ultra-crisp vector line work.",
    longDescription: "Export vector-perfect, lossless PNG screenshots of your PDF pages for presentations, web, and prints.",
    category: "convert-from-pdf",
    categoryLabel: "Convert from PDF",
    iconName: "Image",
    acceptedFormats: [".pdf"],
    outputFormat: "zip",
    maxFiles: 5,
    maxSizeMb: 50,
    features: ["Lossless image fidelity", "High DPI options", "ZIP batch extraction"],
    isImplemented: true,
  },
  {
    id: "pdf-to-excel",
    slug: "pdf-to-excel",
    name: "PDF to Excel",
    description: "Extract data tables from PDF financial statements into editable Excel (.xlsx) workbooks.",
    longDescription: "Intelligently detect table boundaries, headers, numeric columns, and calculate sums into spreadsheet columns.",
    category: "convert-from-pdf",
    categoryLabel: "Convert from PDF",
    iconName: "Table",
    acceptedFormats: [".pdf"],
    outputFormat: "xlsx",
    maxFiles: 5,
    maxSizeMb: 30,
    features: ["Automatic tabular structure detection", "Number formatting preservation", "Multi-page sheet compilation"],
    isImplemented: true,
  },
  {
    id: "pdf-to-powerpoint",
    slug: "pdf-to-powerpoint",
    name: "PDF to PowerPoint",
    description: "Convert PDF presentations into editable PPTX slide decks.",
    longDescription: "Recreate slide layouts from PDF presentations into editable PowerPoint slides.",
    category: "convert-from-pdf",
    categoryLabel: "Convert from PDF",
    iconName: "Presentation",
    acceptedFormats: [".pdf"],
    outputFormat: "pptx",
    maxFiles: 5,
    maxSizeMb: 50,
    features: ["Slide-by-slide conversion", "Text box separation", "Image asset preservation"],
    isImplemented: true,
  },
  {
    id: "pdf-to-txt",
    slug: "pdf-to-txt",
    name: "PDF to Text",
    description: "Extract raw plain text and reading order from PDF files.",
    longDescription: "Quickly extract clean, unformatted plain text strings from your documents for NLP or search indexing.",
    category: "convert-from-pdf",
    categoryLabel: "Convert from PDF",
    iconName: "FileCode",
    acceptedFormats: [".pdf"],
    outputFormat: "txt",
    maxFiles: 10,
    maxSizeMb: 30,
    features: ["Clean text extraction", "Reading order heuristics", "Instant copy to clipboard"],
    isImplemented: true,
  },

  // ================= ORGANIZE PDF =================
  {
    id: "merge-pdf",
    slug: "merge-pdf",
    name: "Merge PDF",
    description: "Combine multiple PDF documents into a single, cohesive file in any desired order.",
    longDescription:
      "Seamlessly unite two or more PDF files into a single master document. Drag and drop to rearrange order, preview pages, and merge in milliseconds.",
    category: "organize",
    categoryLabel: "Organize PDF",
    iconName: "Combine",
    badge: "Popular",
    acceptedFormats: [".pdf"],
    outputFormat: "pdf",
    maxFiles: 50,
    maxSizeMb: 100,
    features: [
      "Visual drag-and-drop file reordering",
      "Interactive page-count inspection",
      "Lossless vector and bookmark preservation",
      "Blazing fast in-browser execution",
    ],
    faqs: [
      {
        question: "How many files can I merge at once?",
        answer: "You can merge up to 50 PDF files simultaneously with zero loss in quality.",
      },
    ],
    isImplemented: true,
  },
  {
    id: "split-pdf",
    slug: "split-pdf",
    name: "Split PDF",
    description: "Separate one PDF into multiple files by custom page ranges, single pages, or page count intervals.",
    longDescription:
      "Divide your PDF documents by page ranges (e.g. 1-3, 4-8), burst every page into individual files, or extract specific pages into a new document.",
    category: "organize",
    categoryLabel: "Organize PDF",
    iconName: "Split",
    badge: "Popular",
    acceptedFormats: [".pdf"],
    outputFormat: "zip",
    maxFiles: 1,
    maxSizeMb: 50,
    features: [
      "Custom page range parser (e.g., 1-5, 8, 11-14)",
      "Extract individual selected pages",
      "Split every N pages interval",
      "Instant ZIP bundle or single PDF download",
    ],
    isImplemented: true,
  },
  {
    id: "organize-pdf",
    slug: "organize-pdf",
    name: "Organize PDF",
    description: "Reorder, rotate, duplicate, and delete pages visually on an interactive page grid.",
    longDescription:
      "Visual workspace for total control over document structure. Drag pages to reorder, rotate individual pages 90°, delete unwanted pages, and duplicate sheets.",
    category: "organize",
    categoryLabel: "Organize PDF",
    iconName: "LayoutGrid",
    badge: "Popular",
    acceptedFormats: [".pdf"],
    outputFormat: "pdf",
    maxFiles: 1,
    maxSizeMb: 50,
    features: [
      "Interactive thumbnail drag & drop reordering",
      "Rotate individual or all pages (90°, 180°, 270°)",
      "One-click page deletion and restoration",
      "Duplicate pages within the document",
    ],
    isImplemented: true,
  },
  {
    id: "rotate-pdf",
    slug: "rotate-pdf",
    name: "Rotate PDF",
    description: "Rotate entire documents or specific landscape/portrait pages permanently.",
    longDescription: "Fix sideways or upside-down scanned pages with permanent 90°, 180°, or 270° rotation.",
    category: "organize",
    categoryLabel: "Organize PDF",
    iconName: "RotateCw",
    acceptedFormats: [".pdf"],
    outputFormat: "pdf",
    maxFiles: 10,
    maxSizeMb: 50,
    features: ["Clockwise and counter-clockwise rotation", "Selective page rotation", "Bulk document rotation"],
    isImplemented: true,
  },
  {
    id: "delete-pages",
    slug: "delete-pages",
    name: "Delete Pages",
    description: "Remove unnecessary or blank pages from your PDF file with visual page selection.",
    longDescription: "Select and prune unneeded, blank, or duplicate pages from any PDF document.",
    category: "organize",
    categoryLabel: "Organize PDF",
    iconName: "Trash2",
    acceptedFormats: [".pdf"],
    outputFormat: "pdf",
    maxFiles: 1,
    maxSizeMb: 50,
    features: ["Click-to-select page deletion", "Bulk range removal", "Live page count update"],
    isImplemented: true,
  },
  {
    id: "extract-pages",
    slug: "extract-pages",
    name: "Extract Pages",
    description: "Pick specific pages from a document and export them into a brand-new PDF.",
    longDescription: "Extract only the pages you need from long reports or contracts into a clean standalone PDF.",
    category: "organize",
    categoryLabel: "Organize PDF",
    iconName: "FileMinus",
    acceptedFormats: [".pdf"],
    outputFormat: "pdf",
    maxFiles: 1,
    maxSizeMb: 50,
    features: ["Visual page selector", "Range picker", "Preserves original quality"],
    isImplemented: true,
  },

  // ================= COMPRESS & OPTIMIZE =================
  {
    id: "compress-pdf",
    slug: "compress-pdf",
    name: "Compress PDF",
    description: "Reduce file size significantly while retaining maximum visual quality and readability.",
    longDescription:
      "Optimize PDF stream dictionaries, compress embedded raster imagery, and remove redundant metadata structures with exact size reduction metrics.",
    category: "compress",
    categoryLabel: "Compress & Optimize",
    iconName: "Minimize2",
    badge: "Popular",
    acceptedFormats: [".pdf"],
    outputFormat: "pdf",
    maxFiles: 10,
    maxSizeMb: 100,
    features: [
      "Three compression modes: Extreme, Recommended, High Quality",
      "Real-time Before vs After file size comparison",
      "Percentage reduction calculator",
      "Removal of duplicate font objects and unreferenced metadata",
    ],
    faqs: [
      {
        question: "Will compression make text blurry?",
        answer: "No! Vector text and line-art remain 100% crisp at any zoom level. Only heavy bitmap image streams are optimized.",
      },
    ],
    isImplemented: true,
  },
  {
    id: "flatten-pdf",
    slug: "flatten-pdf",
    name: "Flatten PDF",
    description: "Merge interactive form fields, annotations, and layers permanently into standard page content.",
    longDescription: "Lock fillable forms and annotations so they cannot be altered or removed by subsequent viewers.",
    category: "compress",
    categoryLabel: "Compress & Optimize",
    iconName: "Layers",
    acceptedFormats: [".pdf"],
    outputFormat: "pdf",
    maxFiles: 10,
    maxSizeMb: 50,
    features: ["Locks form field inputs", "Merges vector layers", "Ensures consistent printing"],
    isImplemented: true,
  },
  {
    id: "remove-metadata",
    slug: "remove-metadata",
    name: "Remove Metadata",
    description: "Strip author names, software signatures, creation dates, and GPS tags from PDF files.",
    longDescription: "Sanitize your documents for privacy before emailing or publishing by purging sensitive document metadata.",
    category: "compress",
    categoryLabel: "Compress & Optimize",
    iconName: "ShieldAlert",
    acceptedFormats: [".pdf"],
    outputFormat: "pdf",
    maxFiles: 10,
    maxSizeMb: 50,
    features: ["Removes author & company metadata", "Strips editing history", "Purges hidden XML namespaces"],
    isImplemented: true,
  },

  // ================= EDIT PDF =================
  {
    id: "edit-pdf",
    slug: "edit-pdf",
    name: "Edit PDF",
    description: "Add text, draw, insert shapes, highlight paragraphs, and apply stamps on your PDF pages.",
    longDescription:
      "Full-featured interactive PDF canvas editor. Draw freehand, insert text callouts, highlight key sections, add geometric shapes, and stamp approval marks.",
    category: "edit",
    categoryLabel: "Edit PDF",
    iconName: "PenTool",
    badge: "Popular",
    acceptedFormats: [".pdf"],
    outputFormat: "pdf",
    maxFiles: 1,
    maxSizeMb: 50,
    features: [
      "Vector text insertion with font, color, and size controls",
      "Freehand drawing pen & marker tool with stroke settings",
      "Geometric shapes (Rectangles, Circles, Arrows, Lines)",
      "Highlighter tool with variable opacity",
      "Business stamps (APPROVED, CONFIDENTIAL, DRAFT, VOID)",
    ],
    isImplemented: true,
  },
  {
    id: "page-numbers",
    slug: "page-numbers",
    name: "Add Page Numbers",
    description: "Insert customizable page numbers into headers or footers with multiple numbering styles.",
    longDescription:
      "Number your PDF pages automatically. Select top/bottom position, left/center/right alignment, font family, size, starting number offset, and format (e.g. 'Page {n} of {total}').",
    category: "edit",
    categoryLabel: "Edit PDF",
    iconName: "Hash",
    acceptedFormats: [".pdf"],
    outputFormat: "pdf",
    maxFiles: 10,
    maxSizeMb: 50,
    features: [
      "Flexible positioning (Top/Bottom, Left/Center/Right)",
      "Custom format templates ('Page {n} of {total}', '{n}', etc.)",
      "Page range exclusion (e.g., skip cover page)",
      "Custom typography and margin offsets",
    ],
    isImplemented: true,
  },
  {
    id: "add-watermark",
    slug: "watermark-pdf",
    name: "Add Watermark",
    description: "Apply custom text or logo watermarks with angle, opacity, and repeat pattern options.",
    longDescription:
      "Stamp documents with copyright, confidentiality warnings, or corporate logos. Control rotation angles (45°, horizontal), opacity, font sizes, and layer positioning.",
    category: "security",
    categoryLabel: "PDF Security",
    iconName: "Stamp",
    badge: "Popular",
    acceptedFormats: [".pdf", ".docx", ".doc", ".jpg", ".jpeg", ".png", ".webp"],
    outputFormat: "pdf",
    maxFiles: 10,
    maxSizeMb: 50,
    features: [
      "Watermark PDF, Word (DOCX/DOC), and Images (JPG/PNG)",
      "Interactive draggable textbox with live visual document canvas",
      "Rotation control (0°, 45°, 90°, -45°)",
      "Custom font families (Helvetica, Times, Courier), colors, and opacity",
      "9-grid position presets and full-page Mosaic/Tile mode",
    ],
    isImplemented: true,
  },

  // ================= PDF SECURITY =================
  {
    id: "protect-pdf",
    slug: "protect-pdf",
    name: "Protect PDF",
    description: "Encrypt documents with standard 128-bit/256-bit AES passwords and restrict permissions.",
    longDescription:
      "Secure confidential documents with military-grade AES password protection. Supports PDF, Word documents, and images with granular printing and extraction restrictions.",
    category: "security",
    categoryLabel: "PDF Security",
    iconName: "Lock",
    badge: "Popular",
    acceptedFormats: [".pdf", ".docx", ".doc", ".jpg", ".jpeg", ".png", ".webp"],
    outputFormat: "pdf",
    maxFiles: 10,
    maxSizeMb: 50,
    features: [
      "AES 256-bit & 128-bit enterprise encryption",
      "Direct conversion & protection for PDF, Word (DOCX/DOC), and Images",
      "Configurable printing, text copying, and modification restrictions",
      "Universal compatibility with Adobe Acrobat, Apple Preview, and Web Viewers",
    ],
    isImplemented: true,
  },
  {
    id: "unlock-pdf",
    slug: "unlock-pdf",
    name: "Unlock PDF",
    description: "Remove security passwords from protected PDFs if you have authorized access credentials.",
    longDescription: "Decrypt and remove password locks from PDFs you own so you can share and edit without friction.",
    category: "security",
    categoryLabel: "PDF Security",
    iconName: "Unlock",
    acceptedFormats: [".pdf"],
    outputFormat: "pdf",
    maxFiles: 10,
    maxSizeMb: 50,
    features: ["Safe authenticated decryption", "Instant password removal", "Fast processing"],
    isImplemented: true,
  },
  {
    id: "sign-pdf",
    slug: "sign-pdf",
    name: "Sign PDF",
    description: "Create digital signatures, draw your hand signature, or upload a signature image stamp.",
    longDescription: "Sign contracts, agreements, and NDAs. Draw on canvas, type with signature fonts, or upload your handwritten signature.",
    category: "security",
    categoryLabel: "PDF Security",
    iconName: "FileSignature",
    badge: "Popular",
    acceptedFormats: [".pdf"],
    outputFormat: "pdf",
    maxFiles: 1,
    maxSizeMb: 50,
    features: ["Canvas signature drawing", "Signature typography generator", "Signature image stamp", "Date & Initial fields"],
    isImplemented: true,
  },
  {
    id: "redact-pdf",
    slug: "redact-pdf",
    name: "Redact PDF",
    description: "Permanently blackout sensitive text, SSNs, credit cards, and addresses from your document.",
    longDescription: "Permanently purge underlying sensitive data and raster streams from the document code rather than just drawing black boxes.",
    category: "security",
    categoryLabel: "PDF Security",
    iconName: "EyeOff",
    acceptedFormats: [".pdf"],
    outputFormat: "pdf",
    maxFiles: 1,
    maxSizeMb: 50,
    features: ["True binary redaction", "Pattern matching for SSNs & emails", "Visual area selection"],
    isImplemented: true,
  },

  // ================= OCR & DOCUMENT PROCESSING =================
  {
    id: "ocr-pdf",
    slug: "ocr-pdf",
    name: "OCR PDF",
    description: "Convert scanned PDFs and photos into searchable, copyable, and indexable text.",
    longDescription:
      "Perform Optical Character Recognition on scanned pages, invoices, and photos to extract high-accuracy selectable text in multiple languages.",
    category: "ocr",
    categoryLabel: "OCR & Text",
    iconName: "ScanText",
    badge: "AI",
    acceptedFormats: [".pdf", ".jpg", ".png", ".jpeg"],
    outputFormat: "pdf",
    maxFiles: 5,
    maxSizeMb: 30,
    features: [
      "Multi-language recognition (English, Spanish, French, German, Chinese, etc.)",
      "Searchable PDF output generation",
      "Instant plain text extraction & clipboard copy",
      "Confidence score indicator",
    ],
    isImplemented: true,
  },
  {
    id: "extract-tables",
    slug: "extract-tables",
    name: "Extract Tables",
    description: "Detect tabular grids in PDFs and export them directly to structured CSV or Excel.",
    longDescription: "AI table recognition extracts bordered and borderless financial tables into clean data spreadsheets.",
    category: "ocr",
    categoryLabel: "OCR & Text",
    iconName: "Grid",
    acceptedFormats: [".pdf", ".jpg", ".png"],
    outputFormat: "xlsx",
    maxFiles: 5,
    maxSizeMb: 30,
    features: ["AI table structure detection", "CSV & Excel export", "Clean header parsing"],
    isImplemented: true,
  },

  // ================= AI TOOLS =================
  {
    id: "ask-pdf",
    slug: "ask-pdf",
    name: "Ask PDF & Chat",
    description: "Chat with your PDF documents with real-time page citations and grounded answers.",
    longDescription:
      "Interact naturally with long PDFs, research papers, legal agreements, and manuals. Ask questions, get referenced answers with page citations, and highlight source text.",
    category: "ai",
    categoryLabel: "AI Document Suite",
    iconName: "MessageSquare",
    badge: "AI",
    acceptedFormats: [".pdf", ".docx", ".txt"],
    outputFormat: "chat",
    maxFiles: 1,
    maxSizeMb: 50,
    features: [
      "Side-by-side interactive reader and AI chat pane",
      "Accurate page citation badges with jump-to-page navigation",
      "Smart suggested follow-up questions",
      "Key takeaways and executive briefing synthesis",
    ],
    isImplemented: true,
  },
  {
    id: "summarize-pdf",
    slug: "summarize-pdf",
    name: "Summarize PDF",
    description: "Generate concise executive summaries, key bullet points, and action items in seconds.",
    longDescription: "Summarize 100-page reports, legal contracts, or research publications into digestible briefs and bulleted insights.",
    category: "ai",
    categoryLabel: "AI Document Suite",
    iconName: "Sparkles",
    badge: "AI",
    acceptedFormats: [".pdf", ".docx", ".txt"],
    outputFormat: "txt",
    maxFiles: 1,
    maxSizeMb: 50,
    features: ["Executive summary generation", "Key takeaways list", "Action items extraction", "Length customization (Short, Medium, In-depth)"],
    isImplemented: true,
  },
  {
    id: "extract-invoice-data",
    slug: "extract-invoice-data",
    name: "Extract Invoice Data",
    description: "Parse invoices, receipts, and POs to extract vendor, totals, tax, line items, and dates into JSON/CSV.",
    longDescription: "Automate accounting data entry by extracting invoice numbers, issue dates, due dates, line items, and totals.",
    category: "ai",
    categoryLabel: "AI Document Suite",
    iconName: "Receipt",
    badge: "AI",
    acceptedFormats: [".pdf", ".jpg", ".png"],
    outputFormat: "json",
    maxFiles: 10,
    maxSizeMb: 30,
    features: ["Line-item extraction", "Vendor & total detection", "JSON & CSV data export"],
    isImplemented: true,
  },
  {
    id: "compare-pdfs",
    slug: "compare-pdfs",
    name: "Compare PDFs",
    description: "Highlight text differences, insertions, and deletions between two document versions side-by-side.",
    longDescription: "Compare two revisions of a contract or specification to instantly spot added, removed, or modified paragraphs.",
    category: "ai",
    categoryLabel: "AI Document Suite",
    iconName: "GitCompare",
    badge: "New",
    acceptedFormats: [".pdf", ".docx"],
    outputFormat: "pdf",
    maxFiles: 2,
    maxSizeMb: 50,
    features: ["Side-by-side visual diffing", "Red/Green change markers", "Summary of revisions"],
    isImplemented: true,
  },
];

export function getToolById(id: string): ToolDefinition | undefined {
  return TOOLS_REGISTRY.find((t) => t.id === id || t.slug === id);
}

export function getToolsByCategory(category: ToolCategory): ToolDefinition[] {
  return TOOLS_REGISTRY.filter((t) => t.category === category);
}

export function getPopularTools(): ToolDefinition[] {
  return TOOLS_REGISTRY.filter((t) => t.badge === "Popular" || t.badge === "AI");
}
